core/urls.py
# -*- Mode: Python; coding: utf-8 -*-
from django.conf.urls import *
from django.contrib import admin
from django.urls import include, path, re_path
from django.conf.urls.static import static
from django.views.generic.base import TemplateView
from django.conf import settings
from rest_framework.urlpatterns import format_suffix_patterns

from . import views

urlpatterns = [
	path('orcamento/<int:id>/', views.orcamento, name='orcamento'),
    path('admin/', admin.site.urls),


]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns = format_suffix_patterns(urlpatterns)

core/base/models.py
from __future__ import unicode_literals
from django.db import models
from django.utils.safestring import mark_safe

class Fornecedor(models.Model):
    nome = models.CharField(max_length=200)

    def __str__(self):
        return self.nome

    class Meta:
        verbose_name = u'Fornecedor'
        verbose_name_plural = u'FORNECEDOR'
        


class Material(models.Model):
    nome = models.CharField(max_length=200)

    def __str__(self):
        return self.nome

    class Meta:
        verbose_name = u'Material'
        verbose_name_plural = u'MATERIAL'

class Compra(models.Model):
    fornecedor = models.ForeignKey(Fornecedor, on_delete=models.CASCADE)
    nota_fiscal = models.CharField(max_length=10)
    data = models.DateField()
    valor_compra = models.DecimalField(max_digits=10,
    decimal_places=2, blank=True, default=0)

    def imprimir(self):
            return mark_safe("""<a href=\"/orcamento/%s/\" target="_blank"><img src=\"/static/images/b_print.png\"></a>""" % self.id)

    class Meta:
        verbose_name = u'Compra'
        verbose_name_plural = u'COMPRAS'
        ordering = ['-data']

class Produto(models.Model):
    material = models.ForeignKey(Material, on_delete=models.CASCADE)
    preco = models.DecimalField(u'PREÇO',max_digits=15,decimal_places=2)
    quantidade = models.DecimalField(u'QUANTIDADE', max_digits=5,decimal_places=0)
    subtotal = models.DecimalField(max_digits=10, decimal_places=2,
    editable=False)
    compra = models.ForeignKey(Compra, on_delete=models.CASCADE)

    def __str__(self):
        return self.material.nome + ",R$" + str(self.preco) +"," + str(self.quantidade) + ",R$" + str(self.subtotal)

    class Meta:
        verbose_name = u'Produto'
        verbose_name_plural = u'PRODUTOS'

    #calculo
    def save(self, *args, **kwargs):
    	self.subtotal = self.preco * self.quantidade 
    	self.compra.valor_compra += self.subtotal
    	self.compra.save()
    	return super(Produto, self).save(*args, **kwargs)

core/base/views.py
from django.shortcuts import render

# Create your views here.

core/views.py
# -*- Mode: Python; coding: utf-8 -*-
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect

from core.base.models import Fornecedor, Compra, Produto, Material



@login_required(redirect_field_name='redirect_to')
def orcamento(request, id=None, *args, **kwargs):
	contexto = {}
	contexto['orcamento'] = Compra.objects.get(id=id)

	return render(request, "orcamento.html", contexto)

templates/orcamento.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-BR">
<head>
  <title>ORÇAMENTO - {{ orcamento.fornecedor.nome }} {{ orcamento.data|date:"d F Y" }}</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
<link rel='stylesheet prefetch' href="{% static 'bootstrap/bootstrap.min.css' %}">

  <link rel="stylesheet" href="{% static 'css/view_impressao.css' %}">
    <style type="text/css" media="print">
  body {
      background: none;
  }
  .quebrapagina {
      visibility: hidden;
      page-break-before: inherit;
  }
thead{
  color: red;
}
@media print{
    /* les styles d'impression commencent ici */
    thead th{
background-color: #f5f5f5 !important;
    }

}

  </style>

</head>
<body>
<div id="geral">
<div class="container">
<div class="topo">
  <div class="row">
      <img class="fl" src="../../static/images/img-proposta.jpg" height="100" alt="" title="" />
  </div>
<div class="row">
  <div class="cliente text-left">
      <h4>Prezado(a): <b>{{orcamento.fornecedor}}</b></h4>
      <h4>Nota Fiscal: <b>{{orcamento.nota_fiscal}}</b></h4><br>
  </div>

  <div class="descricao text-center">
      <h3><b>ORÇAMENTO</b></h3>
  </div>
</div>  
</div>
<div class="row">
    <table class="table table-striped table-bordered table-hover  text-center">
      <thead class="btn-danger print">
        <tr>
          <th>#ID</th>
          <th class="text-center">PRODUTO</th>
          <th>VALOR UNITÁRIO</th>
          <th>QUANTIDADE</th>
        </tr>
      </thead>
      <tbody>
       {% for item_do_orcamento in orcamento.produto_set.all %}
        <tr>
          <td>{{ item_do_orcamento.id }}</td>
          <td class="text-center">{{ item_do_orcamento.material }}</td>
          <td>{{ item_do_orcamento.preco }}</td>
          <td>{{ item_do_orcamento.quantidade }}</td>
        </tr>
         {% endfor %}
      </tbody>
    </table>
    </div>
</div>
<div class="container">
  <div class="row">
    <h4 class=" id_valor text-right">VALOR TOTAL <strong>R$: {{ orcamento.valor_compra }}</strong></h4>
  </div>
  <div class="row">
    <h3 class="id_data text-right"><b>IMPERATRIZ-MA {{ orcamento.data|date|upper }}</b></h3>
  </div>
  </div>
  <div class="separador assi_wllisses text-center">
    <b>
      Wings Design - Marketing | Design | Serviços<br>
      Cpf: 000.000.000-000
  <img class="fl" src="../../static/images/ass_wllisses.png" height="100" alt="" title="" />
    </b>
  </div><br>
</div>
<script src="{% static 'bootstrap/jquery.min.js' %}"></script>
</body>
</html>